1 commit
Crazerr12/ToDoApp pull request #2
Opened 2022-04-24 07:29 UTC by Crazerr12

2022-04-25 20:21 UTC, Alexandr-Prokin requested changes

2022-04-25 20:21 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/Validator.kt
> +        if (text?.isEmpty() == false && text.length!! >=7 && text.contains("@")) null
до и после знака условия, пробел    >=

2022-04-25 20:21 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/MainActivity.kt
> +            val duration = Toast.LENGTH_SHORT
это лишнее. сразу передавать нужно

2022-04-25 20:21 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/MainActivity.kt
> +            val toastMessage = "Success!"
строку в ресурсы убери, если получится, если нет то тоже сразу в тосте

2022-04-25 20:21 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/MainActivity.kt
> +            val toast = Toast.makeText(applicationContext, toastMessage, duration)
лучше сделать отдельную функцию, в которую передается текст, и она вызывает тост, и причем тост два раза показывает, первый раз тут

2022-04-25 20:21 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/MainActivity.kt
> +                toast.show()
второй раз тут

2022-04-25 20:21 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/MainActivity.kt
> +
можно обернуть в with(binding), если получится, сделай

2022-04-25 20:21 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/MainActivity.kt
> +
лишние пробелы не забывай убирать

2022-04-25 20:21 UTC, Alexandr-Prokin commented on app/build.gradle
> +    viewBinding {
buildFeatures{
        viewBinding true
    }
    
    замени

2022-04-25 20:21 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/MainActivity.kt
> +            else null
else тут не нужно

2022-04-25 20:21 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +    <ImageView
ну и это уберешь =)

2022-05-01 07:48 UTC, Alexandr-Prokin requested changes

2022-05-01 07:48 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/MainActivity.kt
> +    fun toastShow() =
в конструктор лучше передавать текст, который нужно показать

2022-05-01 07:48 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/MainActivity.kt
> +        val toast1 = toastShow()
а зачем это? можно же сразу функция вызвать, без ее копии

2022-05-01 07:48 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/MainActivity.kt
> +                toast1
тут сразу вызови функцию и передай в нее текст, еще обрати внимание на то, когда у тебя появляется Toast, после того как появилась активность или после того как нажал на кнопку (когда все ок)

2022-05-03 13:57 UTC, Crazerr12 commented on app/src/main/java/com/example/todoapp/MainActivity.kt
> +                toast1
после того, как нажал на кнопку

2022-05-03 17:46 UTC, Alexandr-Prokin approved these changes

2022-05-03 17:50 UTC, merged