commit
Crazerr12/ToDoApp pull request #9
Opened 2022-09-24 18:11 UTC by Crazerr12

2022-09-29 17:42 UTC, Alexandr-Prokin requested changes

2022-09-29 17:42 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/presentation/category/CategoryFragment.kt
> +    lateinit var preferences: SharedPreferences
Объявили что будет инициализирован, но в итоге он не инициализирован и выдает ошибку

2022-09-29 17:42 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/presentation/login/LoginFragment.kt
> +                            editor.putString("TOKEN", token)
токен в шаред преференс положил, а не сохранил, там пусто, про область видимости не забавай

2022-09-29 17:42 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/presentation/category/CategoryFragment.kt
> +                    val adapter = TasksAdapter()
на уровень функции перенеси, а сейчас получается  у тебя адаптер внутри запроса живет

2022-09-29 17:42 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/presentation/category/CategoryFragment.kt
> +                    adapter.submitList(tasks)
это тут пусть

2022-09-29 17:42 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/presentation/category/CategoryFragment.kt
> +                    binding.buttonAdd.setOnClickListener {
кнопку тоже из запроса убери

2022-09-29 17:42 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/presentation/models/TaskModel.kt
> +    val id: Int,
разве int???

2022-10-04 07:22 UTC, Crazerr12 commented
А как я могу сохранить токен?

2022-10-06 11:21 UTC, Alexandr-Prokin requested changes

2022-10-06 11:21 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/presentation/category/CategoryFragment.kt
> +    lateinit var preferences: SharedPreferences
не инициализирован, а ты из него хочешь получить значение, поэтому и крашится

2022-10-14 10:57 UTC, Alexandr-Prokin requested changes

2022-10-14 10:57 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/presentation/login/LoginFragment.kt
> +                            editor.putString("TOKEN", token)
cразу после этой строки editor.apply()

2022-10-14 10:57 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/presentation/login/LoginFragment.kt
>                  editor.putString("EMAIL", email)
уже не нужно почту сохранять в шаред, почта потом с сервера придет

2022-10-22 16:46 UTC, Crazerr12 commented
Commit #2 неправильный, не смотрите его

2022-10-22 17:32 UTC, Alexandr-Prokin requested changes
Задание следующее. Внести правки по коду. 
Переделать экран профиля, чтобы взаимодействовал с сервером, картинку для профиля пока оставь, сделаем потом.

2022-10-22 17:32 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/presentation/login/LoginFragment.kt
>                  editor.putString("EMAIL", email)
Это можно удалить, почта приходит с сервера

2022-10-22 17:32 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/presentation/login/LoginFragment.kt
>                  editor.putBoolean("REMEMBER", true)
Это тоже удалить

2022-10-26 18:27 UTC, merged